name: Modular GraphQL Demo
on:
  push:
    paths:
      - 'services/**'
      - package.json
      - .github/workflows/modular-graphql-demo.yml
      - yarn.lock
jobs:
  modular_graphql_demo_test:
    name: Tests (rename)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - name: Cache inputs and outputs
        id: cache
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn install
#        if: steps.cache.outputs.cache-hit != 'true'
        run: NOYARNPOSTINSTALL=1 yarn install